title: CATE
author: Liam Wyllie
email: lwyll002@gold.ac.uk
description: Project blog for the CATE program, updated with my progress and findings.

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

  social_links:
    github: lrwz
    rss: rss
    
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages: .

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
